on:
  pull_request:
    types:
      - closed

jobs:
  if_merged:
    if: github.event.pull_request.merged && startsWith(github.base_ref, 'support')
    runs-on: ubuntu-latest
    steps:
      - name: Dump GitHub context
        env:
          GITHUB_CONTEXT: ${{ toJson(github) }}
        run: echo "GITHUB_CONTEXT = $GITHUB_CONTEXT"

      - name: Get short SHA
        id: get-short-sha
        run: |
          sha=$(echo ${{github.sha}} | cut -c 1-7)
          echo "sha=$sha" >> $GITHUB_OUTPUT

      - name: Get Branch Name
        id: get-branch-name
        run: |
          echo "branch=${{ steps.get-short-sha.outputs.sha }}=>develop" >> $GITHUB_OUTPUT

      - name: Debug
        id: debug
        run: |
            {
              echo "### Workflow variables"
              echo "| Variable   | Value                                       |"
              echo "| ---------- | ------------------------------------------- |"
              echo "| sha        | ${{ steps.get-short-sha.outputs.sha }}      |"
              echo "| branch     | ${{ steps.get-branch-name.outputs.branch }} |"
            } >> $GITHUB_STEP_SUMMARY

      - name: Checkout Support
        uses: actions/checkout@v3        
        with:
          ref: ${{ github.base_ref }}
      
      # do I ned to checkout develop ? 
      # maybe i could judt do:
      #   git checkout -b ${{ steps.get-branch-name.outputs.branch }} origin/develop
      # - name: Checkout Develop Branch
      #   uses: actions/checkout@v3
      #   with:
      #     ref: develop

      - name: Create Branch off Develop
        run: |
          git config user.name github-actions
          git config user.email github-actions@github.com
          git checkout -b ${{ steps.get-branch-name.outputs.branch }} origin/develop
      
      # - name: Cherry pick the merge commit
      #   run: |
      #     git config user.name github-actions
      #     git config user.email github-actions@github.com      
      #     git cherry-pick -m 1 ${{ github.sha }}

      - name: Merge support branch into develop
        run: |
          git config user.name github-actions
          git config user.email github-actions@github.com      
          git merge ${{ github.base_ref }}
      

      - name: Push new branch
        run: |
          git config user.name github-actions
          git config user.email github-actions@github.com      
          git push -f origin ${{ steps.get-branch-name.outputs.branch }}            
